# Generated by Django 4.1.1 on 2022-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='sessionID',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
